services:
    proxy:
        image: caddy:2-alpine
        container_name: pixmark-proxy
        ports:
            - "8080:80"
            - "4443:443"
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./docker/certs:/etc/certs
        depends_on:
            - backend
            - frontend
        networks:
            - pixmark

    backend:
        build:
            context: backend
        container_name: pixmark-backend
        volumes:
            - ./backend:/app
        environment:
            - APP_ENV=${APP_ENV:-dev}
        networks:
            - pixmark
        command: [ "frankenphp", "run", "--config", "/app/Caddyfile" ]

    frontend:
        build:
            context: frontend
        container_name: pixmark-frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=${NODE_ENV:-development}
        networks:
            - pixmark
        command: [ "npm", "run", "dev" ]

networks:
    pixmark:
        driver: bridge
