# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']
    http_method_override: false
    router:
        utf8: true
        default_uri: '/back'
    assets:
        base_path: '/back'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
